### ISSUE TITLE
CLI doesn't work on Windows

### ISSUE THREAD

**Issue by wKovacs64** [jacobparis-insiders/sly#13]
The bin script for the CLI is a bash shell script, which doesn't work on Windows (without users doing things you can't really expect them to do). Can we convert it to a Node script so Sly CLI works cross-platform?

I played around with some solutions and have it working locally by simply pointing bin at `./dist/index.js` directly as I didn't see the need for a TS loader at all, but I also have a version using [`tsx`](https://npm.im/tsx) instead of your custom `ts-loader.js` in case there really is a need to process TS files.

Thoughts? Happy to open a PR if you want.

Thanks.

**Comment by jacobparis** [comment]
Have you tried on the latest version? This issue might be related

https://github.com/jacobparis-insiders/sly/issues/7

The use-case for the TS Loader is allowing users to specify transformer files in Typescript

**Comment by wKovacs64** [comment]
> Have you tried on the latest version (1.5.0)? This issue might be related

Yep, I'm using 1.5.0.
 
> The use-case for the TS Loader is allowing users to specify transformer files in Typescript

Ah, gotcha. 👍
