### ISSUE TITLE
tabler-icons registry is broken

### ISSUE THREAD

**Issue by arpitdalal** [jacobparis-insiders/sly#48]
[tabler-icons renamed `master` to `main`](https://github.com/tabler/tabler-icons/tree/main/icons) and that broke the registry [here](https://sly-cli.fly.dev/registry/tabler-icons.json). A simple change from `master` to `main` [here](https://github.com/jacobparis-insiders/sly/blob/main/site/app/routes/registry%2B/tabler-icons%5B.json%5D.ts#L22) and [here](https://github.com/jacobparis-insiders/sly/blob/main/site/app/routes/registry%2B/tabler-icons.%24name%5B.json%5D.ts#L15) will fix it.

**Comment by arpitdalal** [comment]
Looking further into it, I found out that they have restructured the `icons` folder. Now, they have `filled` and `outline` folders too

**Comment by jacobparis** [comment]
Thanks for reporting this! I've updated the lib to work with the new structure and will deploy shortly if tests pass

**Comment by arpitdalal** [comment]
Will this break old icons that don't have the variants in their names?
