### ISSUE TITLE
support for remixicons

### ISSUE THREAD

**Issue by jjenzz** [jacobparis-insiders/sly#57]
i started to have a little play with this today but we're using [remixicons](https://remixicon.com/) which doesn't appear to exist in [the supported registries](https://github.com/jacobparis-insiders/sly/tree/main/site/app/routes/registry%2B). i'd love to request support for that ☺️ 

thanks for a great tool, i'm excited to give it a try!

**Comment by jacobparis** [comment]
Hey Jenna! I've just added remixicons in #58 

This is the best I can do at the moment until I add CLI support for variants (#35) so it's fine if you know roughly what icon you want but exploring is a bit of a pain 

<img width="626" alt="image" src="https://github.com/user-attachments/assets/5a7f8aee-5959-4197-b391-382d8b0e716f">

**Comment by jjenzz** [comment]
oh wow, that's amazing! thanks for the speedy update 🫶

**Comment by jacobparis** [comment]
There's a really annoying internal cache that I don't know why I ever thought it was a good idea

Run `pnpx @sly-cli/sly refresh` to clear it and I'll start testing a new release that finally gets rid of it, it probably causes me more grief than anyone

**Comment by jjenzz** [comment]
that worked, thanks a ton ☺️
